services:
  db:
    image: pgvector/pgvector:pg16
    container_name: 'rag-db'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mastra}
    volumes:
      - pgdata:/var/lib/postgresql/data
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
  chroma:
    image: chromadb/chroma
    ports:
      - 8000:8000
volumes:
  pgdata:
